participant_mapping = {
    'participant': {
        'Angestellter': ['Angestellte', 'Angestellte', 'Angestellte', 'Angestellte'],
        'Anwohner': ['Anwohner', 'Anwohnerin', 'Anwohnere', 'Anwohner*in'],
        'Auftraggeber': ['Auftraggeber', 'Auftraggeberin', 'Auftraggebere', 'Auftraggeber*in'],
        'Auszubildender': ['Auszubildende', 'Auszubildende', 'Auszubildende', 'Auszubildende'],
        'Besitzer': ['Besitzer', 'Besitzerin', 'Besitzere', 'Besitzer*in'],
        'Besucher': ['Besucher', 'Besucherin', 'Besuchere', 'Besucher*in'],
        'Demonstrant': ['Demonstrant', 'Demonstrantin', 'Demonstrante', 'Demonstrant*in'],
        'Fußgänger': ['Fußgänger', 'Fußgängerin', 'Fußgängere', 'Fußgänger*in'],
        'Grundstücksbesitzer': ['Grundstücksbesitzer', 'Grundstücksbesitzerin', 'Grundstücksbesitzere', 'Grundstücksbesitzer*in'],
        'Heranwachsender': ['Heranwachsende', 'Heranwachsende', 'Heranwachsende', 'Heranwachsende'],
        'Käufer': ['Käufer', 'Käuferin', 'Käufere', 'Käufer*in'],
        'Klient': ['Klient', 'Klientin', 'Kliente', 'Klient*in'],
        'Kunde': ['Kunde', 'Kundin', 'Kunde', 'Kund*in'],
        'Mandant': ['Mandant', 'Mandantin', 'Mandante', 'Mandant*in'],
        'Mieter': ['Mieter', 'Mieterin', 'Mietere', 'Mieter*in'],
        'Patient': ['Patient', 'Patientin', 'Patiente', 'Patient*in'],
        'Praktikant': ['Praktikant', 'Praktikantin', 'Praktikante', 'Praktikant*in'],
        'Schaulustiger': ['Schaulustige', 'Schaulustige', 'Schaulustige', 'Schaulustige'],
        'Schüler': ['Schüler', 'Schülerin', 'Schülere', 'Schüler*in'],
        'Steuerzahler': ['Steuerzahler', 'Steuerzahlerin', 'Steuerzahlere', 'Steuerzahler*in'],
        'Student': ['Student', 'Studentin', 'Studente', 'Student*in'],
        'Verstorbener': ['Verstorbene', 'Verstorbene', 'Verstorbene', 'Verstorbene'],
        'Verunglückter': ['Verunglückte', 'Verunglückte', 'Verunglückte', 'Verunglückte'],
        'Zeuge': ['Zeuge', 'Zeugin', 'Zeuge', 'Zeug*in'],
        'Zuschauer': ['Zuschauer', 'Zuschauerin', 'Zuschauere', 'Zuschauer*in'],
    }
}
